server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    charset utf-8;

    location / {
        return 302 $scheme://$http_host/painel/;
    }

    location /painel/api/ {
        proxy_pass http://coreps_api:3001/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /painel/ {
        try_files $uri $uri/ /painel/index.html;
    }

    location ~ /\.(?!well-known) {
        deny all;
    }

    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
}
